name: spainAI
dependencies:
  - cudatoolkit=10.1
  - holoviews=1.14.*
  - jupyter=1.0.*
  - keras-gpu=2.4.*
  - pytorch::torchaudio=0.7.*
  - pytorch::torchvision=0.8.*
  - pandas=1.1.*
  - pip=19.3.1
  - pytorch::pytorch=1.7.*
  - scikit-learn=0.23.*
  - spacy=2.3.*  # python -m spacy download en_core_web_sm
  - pip:
    - BackTranslation==0.3.*
    - fairseq==0.10.*
    - fastBPE==0.1.*
    - nlpaug==1.1.*
    - nltk==3.5
    - sacremoses==0.0.43
    - scikit-optimize==0.8.*
    - transformers==4.2.0
    - transformers[sentencepiece]==0.1.91
    - xgboost==1.3.1
